# Generated by Django 3.0.5 on 2020-04-08 21:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import ppe.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.TextField()),
                ('item', models.TextField(choices=[('faceshield', 'faceshield'), ('gown', 'gown'), ('gown_material', 'gown_material')])),
                ('units', models.IntegerField()),
                ('unit', models.TextField(choices=[('each', 'each'), ('yard', 'yard'), ('lb', 'lb')], default=ppe.models.Unit['each'])),
                ('delivery_date', models.DateField(null=True)),
                ('cost', models.IntegerField()),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('counterparty', models.TextField()),
                ('delivery_to', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
