# Generated by Django 3.0.5 on 2020-04-09 22:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import ppe.dataclasses
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.TextField(choices=[('EDC_PPE', 'EDC_PPE')])),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.TextField(choices=[('EDC_PPE', 'EDC_PPE')])),
                ('order_type', models.TextField(choices=[('Purchase', 'Purchase'), ('Make', 'Make')])),
                ('item', models.TextField(choices=[('faceshield', 'faceshield'), ('gown', 'gown'), ('gown_material', 'gown_material'), ('coveralls', 'coveralls'), ('n95_mask_non_surgical', 'n95_mask_non_surgical'), ('n95_mask_surgical', 'n95_mask_surgical'), ('kn95_mask', 'kn95_mask'), ('surgical_mask', 'surgical_mask'), ('mask_other', 'mask_other'), ('goggles', 'goggles'), ('gloves', 'gloves'), ('ventilators_full_service', 'ventilators_full_service'), ('ventilators_non_full_service', 'ventilators_non_full_service'), ('ppe_other', 'ppe_other'), ('unknown', 'unknown')])),
                ('quantity', models.IntegerField()),
                ('unit', models.TextField(choices=[('each', 'each'), ('yard', 'yard'), ('lb', 'lb')], default=ppe.dataclasses.Unit['each'])),
                ('vendor', models.TextField()),
                ('cost', models.IntegerField(null=True)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.TextField(choices=[('EDC_PPE', 'EDC_PPE')])),
                ('item', models.TextField(choices=[('faceshield', 'faceshield'), ('gown', 'gown'), ('gown_material', 'gown_material'), ('coveralls', 'coveralls'), ('n95_mask_non_surgical', 'n95_mask_non_surgical'), ('n95_mask_surgical', 'n95_mask_surgical'), ('kn95_mask', 'kn95_mask'), ('surgical_mask', 'surgical_mask'), ('mask_other', 'mask_other'), ('goggles', 'goggles'), ('gloves', 'gloves'), ('ventilators_full_service', 'ventilators_full_service'), ('ventilators_non_full_service', 'ventilators_non_full_service'), ('ppe_other', 'ppe_other'), ('unknown', 'unknown')])),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('satisfied', models.BooleanField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppe.Hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.TextField(choices=[('EDC_PPE', 'EDC_PPE')])),
                ('delivery_date', models.DateField(null=True)),
                ('quantity', models.IntegerField()),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppe.Purchase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
