# Generated by Django 3.0.5 on 2020-04-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0002_auto_20200409_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
