# Generated by Django 3.0.5 on 2020-04-10 16:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ppe", "0004_auto_20200409_2232"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_source",
                    models.TextField(
                        choices=[
                            ("EDC_PPE", "EDC_PPE"),
                            ("EDC_MAKE", "EDC_MAKE"),
                            ("INVENTORY", "INVENTORY"),
                        ],
                        default=None,
                    ),
                ),
                ("replaced", models.BooleanField(default=False)),
                (
                    "item",
                    models.TextField(
                        choices=[
                            ("faceshield", "faceshield"),
                            ("gown", "gown"),
                            ("gown_material", "gown_material"),
                            ("coveralls", "coveralls"),
                            ("n95_mask_non_surgical", "n95_mask_non_surgical"),
                            ("n95_mask_surgical", "n95_mask_surgical"),
                            ("kn95_mask", "kn95_mask"),
                            ("surgical_mask", "surgical_mask"),
                            ("mask_other", "mask_other"),
                            ("goggles", "goggles"),
                            ("generic_eyeware", "generic_eyeware"),
                            ("gloves", "gloves"),
                            ("ventilators_full_service", "ventilators_full_service"),
                            (
                                "ventilators_non_full_service",
                                "ventilators_non_full_service",
                            ),
                            ("bipap_machines", "bipap_machines"),
                            ("ppe_other", "ppe_other"),
                            ("unknown", "unknown"),
                            ("body_bags", "body_bags"),
                        ],
                        default=None,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("raw_data", django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={"abstract": False,},
        ),
        migrations.AlterField(
            model_name="delivery",
            name="data_source",
            field=models.TextField(
                choices=[
                    ("EDC_PPE", "EDC_PPE"),
                    ("EDC_MAKE", "EDC_MAKE"),
                    ("INVENTORY", "INVENTORY"),
                ],
                default=None,
            ),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="data_source",
            field=models.TextField(
                choices=[
                    ("EDC_PPE", "EDC_PPE"),
                    ("EDC_MAKE", "EDC_MAKE"),
                    ("INVENTORY", "INVENTORY"),
                ],
                default=None,
            ),
        ),
        migrations.AlterField(
            model_name="need",
            name="data_source",
            field=models.TextField(
                choices=[
                    ("EDC_PPE", "EDC_PPE"),
                    ("EDC_MAKE", "EDC_MAKE"),
                    ("INVENTORY", "INVENTORY"),
                ],
                default=None,
            ),
        ),
        migrations.AlterField(
            model_name="need",
            name="item",
            field=models.TextField(
                choices=[
                    ("faceshield", "faceshield"),
                    ("gown", "gown"),
                    ("gown_material", "gown_material"),
                    ("coveralls", "coveralls"),
                    ("n95_mask_non_surgical", "n95_mask_non_surgical"),
                    ("n95_mask_surgical", "n95_mask_surgical"),
                    ("kn95_mask", "kn95_mask"),
                    ("surgical_mask", "surgical_mask"),
                    ("mask_other", "mask_other"),
                    ("goggles", "goggles"),
                    ("generic_eyeware", "generic_eyeware"),
                    ("gloves", "gloves"),
                    ("ventilators_full_service", "ventilators_full_service"),
                    ("ventilators_non_full_service", "ventilators_non_full_service"),
                    ("bipap_machines", "bipap_machines"),
                    ("ppe_other", "ppe_other"),
                    ("unknown", "unknown"),
                    ("body_bags", "body_bags"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="data_source",
            field=models.TextField(
                choices=[
                    ("EDC_PPE", "EDC_PPE"),
                    ("EDC_MAKE", "EDC_MAKE"),
                    ("INVENTORY", "INVENTORY"),
                ],
                default=None,
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="item",
            field=models.TextField(
                choices=[
                    ("faceshield", "faceshield"),
                    ("gown", "gown"),
                    ("gown_material", "gown_material"),
                    ("coveralls", "coveralls"),
                    ("n95_mask_non_surgical", "n95_mask_non_surgical"),
                    ("n95_mask_surgical", "n95_mask_surgical"),
                    ("kn95_mask", "kn95_mask"),
                    ("surgical_mask", "surgical_mask"),
                    ("mask_other", "mask_other"),
                    ("goggles", "goggles"),
                    ("generic_eyeware", "generic_eyeware"),
                    ("gloves", "gloves"),
                    ("ventilators_full_service", "ventilators_full_service"),
                    ("ventilators_non_full_service", "ventilators_non_full_service"),
                    ("bipap_machines", "bipap_machines"),
                    ("ppe_other", "ppe_other"),
                    ("unknown", "unknown"),
                    ("body_bags", "body_bags"),
                ],
                default=None,
            ),
        ),
    ]
