# Generated by Django 3.0.5 on 2020-04-12 15:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0008_auto_20200411_1643'),
    ]

    operations = [
        migrations.RenameModel('Delivery', 'ScheduledDelivery')
    ]
