# Generated by Django 3.0.5 on 2020-04-12 15:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ppe", "0009_auto_20200412_1517"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                (
                    "tpe",
                    models.TextField(
                        choices=[
                            ("government", "government"),
                            ("hospital", "hospital"),
                            ("ems", "ems"),
                            ("nursing_home", "nursing_home"),
                            ("clinic", "clinic"),
                        ],
                        default=None,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AlterField(
            model_name="dataimport",
            name="status",
            field=models.TextField(
                choices=[
                    ("active", "active"),
                    ("replaced", "replaced"),
                    ("candidate", "candidate"),
                    ("cancelled", "cancelled"),
                ],
                default=None,
            ),
        ),
        migrations.AlterField(
            model_name="scheduleddelivery",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="ppe.Purchase",
            ),
        ),
        migrations.CreateModel(
            name="InboundReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date_received", models.DateTimeField()),
                (
                    "supplier",
                    models.TextField(
                        choices=[
                            ("dcas_donations", "dcas_donations"),
                            ("dcas_procurement", "dcas_procurement"),
                            ("other", "other"),
                        ],
                        default=None,
                    ),
                ),
                ("description", models.TextField()),
                ("quantity", models.IntegerField()),
                ("inbound_id", models.TextField()),
                ("item_id", models.TextField()),
                (
                    "item",
                    models.TextField(
                        choices=[
                            ("faceshield", "faceshield"),
                            ("gown", "gown"),
                            ("gown_material", "gown_material"),
                            ("coveralls", "coveralls"),
                            ("n95_mask_non_surgical", "n95_mask_non_surgical"),
                            ("n95_mask_surgical", "n95_mask_surgical"),
                            ("kn95_mask", "kn95_mask"),
                            ("surgical_mask", "surgical_mask"),
                            ("mask_other", "mask_other"),
                            ("goggles", "goggles"),
                            ("generic_eyeware", "generic_eyeware"),
                            ("gloves", "gloves"),
                            ("ventilators_full_service", "ventilators_full_service"),
                            (
                                "ventilators_non_full_service",
                                "ventilators_non_full_service",
                            ),
                            ("bipap_machines", "bipap_machines"),
                            ("ppe_other", "ppe_other"),
                            ("unknown", "unknown"),
                            ("body_bags", "body_bags"),
                        ],
                        default=None,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ppe.DataImport"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="FacilityDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "item",
                    models.TextField(
                        choices=[
                            ("faceshield", "faceshield"),
                            ("gown", "gown"),
                            ("gown_material", "gown_material"),
                            ("coveralls", "coveralls"),
                            ("n95_mask_non_surgical", "n95_mask_non_surgical"),
                            ("n95_mask_surgical", "n95_mask_surgical"),
                            ("kn95_mask", "kn95_mask"),
                            ("surgical_mask", "surgical_mask"),
                            ("mask_other", "mask_other"),
                            ("goggles", "goggles"),
                            ("generic_eyeware", "generic_eyeware"),
                            ("gloves", "gloves"),
                            ("ventilators_full_service", "ventilators_full_service"),
                            (
                                "ventilators_non_full_service",
                                "ventilators_non_full_service",
                            ),
                            ("bipap_machines", "bipap_machines"),
                            ("ppe_other", "ppe_other"),
                            ("unknown", "unknown"),
                            ("body_bags", "body_bags"),
                        ],
                        default=None,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ppe.Facility"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ppe.DataImport"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="facility",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ppe.DataImport"
            ),
        ),
    ]
