# Generated by Django 3.0.5 on 2020-04-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ppe', '0010_auto_20200412_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataimport',
            old_name='data_source',
            new_name='data_file'
        ),
    ]
