# Generated by Django 3.0.5 on 2020-04-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0012_auto_20200412_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitydelivery',
            name='item',
            field=models.TextField(choices=[('faceshield', 'faceshield'), ('gown', 'gown'), ('gown_material', 'gown_material'), ('coveralls', 'coveralls'), ('ponchos', 'ponchos'), ('scrubs', 'scrubs'), ('n95_mask_non_surgical', 'n95_mask_non_surgical'), ('n95_mask_surgical', 'n95_mask_surgical'), ('kn95_mask', 'kn95_mask'), ('surgical_mask', 'surgical_mask'), ('mask_other', 'mask_other'), ('goggles', 'goggles'), ('generic_eyeware', 'generic_eyeware'), ('gloves', 'gloves'), ('ventilators_full_service', 'ventilators_full_service'), ('ventilators_non_full_service', 'ventilators_non_full_service'), ('bipap_machines', 'bipap_machines'), ('ppe_other', 'ppe_other'), ('unknown', 'unknown'), ('body_bags', 'body_bags')], default=None),
        ),
        migrations.AlterField(
            model_name='inboundreceipt',
            name='item',
            field=models.TextField(choices=[('faceshield', 'faceshield'), ('gown', 'gown'), ('gown_material', 'gown_material'), ('coveralls', 'coveralls'), ('ponchos', 'ponchos'), ('scrubs', 'scrubs'), ('n95_mask_non_surgical', 'n95_mask_non_surgical'), ('n95_mask_surgical', 'n95_mask_surgical'), ('kn95_mask', 'kn95_mask'), ('surgical_mask', 'surgical_mask'), ('mask_other', 'mask_other'), ('goggles', 'goggles'), ('generic_eyeware', 'generic_eyeware'), ('gloves', 'gloves'), ('ventilators_full_service', 'ventilators_full_service'), ('ventilators_non_full_service', 'ventilators_non_full_service'), ('bipap_machines', 'bipap_machines'), ('ppe_other', 'ppe_other'), ('unknown', 'unknown'), ('body_bags', 'body_bags')], default=None),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item',
            field=models.TextField(choices=[('faceshield', 'faceshield'), ('gown', 'gown'), ('gown_material', 'gown_material'), ('coveralls', 'coveralls'), ('ponchos', 'ponchos'), ('scrubs', 'scrubs'), ('n95_mask_non_surgical', 'n95_mask_non_surgical'), ('n95_mask_surgical', 'n95_mask_surgical'), ('kn95_mask', 'kn95_mask'), ('surgical_mask', 'surgical_mask'), ('mask_other', 'mask_other'), ('goggles', 'goggles'), ('generic_eyeware', 'generic_eyeware'), ('gloves', 'gloves'), ('ventilators_full_service', 'ventilators_full_service'), ('ventilators_non_full_service', 'ventilators_non_full_service'), ('bipap_machines', 'bipap_machines'), ('ppe_other', 'ppe_other'), ('unknown', 'unknown'), ('body_bags', 'body_bags')], default=None),
        ),
        migrations.AlterField(
            model_name='need',
            name='item',
            field=models.TextField(choices=[('faceshield', 'faceshield'), ('gown', 'gown'), ('gown_material', 'gown_material'), ('coveralls', 'coveralls'), ('ponchos', 'ponchos'), ('scrubs', 'scrubs'), ('n95_mask_non_surgical', 'n95_mask_non_surgical'), ('n95_mask_surgical', 'n95_mask_surgical'), ('kn95_mask', 'kn95_mask'), ('surgical_mask', 'surgical_mask'), ('mask_other', 'mask_other'), ('goggles', 'goggles'), ('generic_eyeware', 'generic_eyeware'), ('gloves', 'gloves'), ('ventilators_full_service', 'ventilators_full_service'), ('ventilators_non_full_service', 'ventilators_non_full_service'), ('bipap_machines', 'bipap_machines'), ('ppe_other', 'ppe_other'), ('unknown', 'unknown'), ('body_bags', 'body_bags')]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.TextField(choices=[('faceshield', 'faceshield'), ('gown', 'gown'), ('gown_material', 'gown_material'), ('coveralls', 'coveralls'), ('ponchos', 'ponchos'), ('scrubs', 'scrubs'), ('n95_mask_non_surgical', 'n95_mask_non_surgical'), ('n95_mask_surgical', 'n95_mask_surgical'), ('kn95_mask', 'kn95_mask'), ('surgical_mask', 'surgical_mask'), ('mask_other', 'mask_other'), ('goggles', 'goggles'), ('generic_eyeware', 'generic_eyeware'), ('gloves', 'gloves'), ('ventilators_full_service', 'ventilators_full_service'), ('ventilators_non_full_service', 'ventilators_non_full_service'), ('bipap_machines', 'bipap_machines'), ('ppe_other', 'ppe_other'), ('unknown', 'unknown'), ('body_bags', 'body_bags')], default=None),
        ),
    ]
