# Generated by Django 3.0.5 on 2020-04-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0014_facilitydelivery_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='received_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
