# Generated by Django 3.0.5 on 2020-04-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppe", "0016_auto_20200414_1528"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataimport",
            name="current_as_of",
            field=models.DateField(null=True),
        ),
    ]
