# Generated by Django 3.0.5 on 2020-04-17 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ppe", "0017_dataimport_current_as_of"),
        ("ppe", "0017_auto_20200416_2258"),
    ]

    operations = []
