# Generated by Django 3.0.5 on 2020-04-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ppe", "0018_merge_20200417_0336"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="donation_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
