# Generated by Django 3.0.5 on 2020-04-18 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ppe", "0019_purchase_donation_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedImport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.BinaryField()),
                ("file_name", models.TextField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("current_as_of", models.DateField()),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
