# Generated by Django 3.0.5 on 2020-05-17 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0022_auto_20200503_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitydelivery',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ppe.Facility'),
        ),
    ]
