# Generated by Django 3.0.5 on 2020-05-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0023_auto_20200517_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimport',
            name='data_file',
            field=models.TextField(choices=[('PPE_ORDERINGCHARTS_DATE_XLSX', 'PPE_ORDERINGCHARTS_DATE_XLSX'), ('SUPPLIERS_PARTNERS_XLSX', 'SUPPLIERS_PARTNERS_XLSX'), ('INVENTORY', 'INVENTORY'), ('FACILITY_DELIVERIES', 'FACILITY_DELIVERIES'), ('HOSPITAL_DEMANDS', 'HOSPITAL_DEMANDS'), ('CSH_DONATIONS', 'CSH_DONATIONS')], db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='dataimport',
            name='status',
            field=models.TextField(choices=[('active', 'active'), ('replaced', 'replaced'), ('candidate', 'candidate'), ('cancelled', 'cancelled')], db_index=True, default=None),
        ),
    ]
