import json
from enum import Enum

from django.core.serializers.json import DjangoJSONEncoder

from ppe.data_mapping.utils import ErrorCollector


class ImportedRow:
    """
    Importers convert spreadsheet rows into implementors of this type.
    The key function to define is `to_objects()` which returns a list of database objects
    generated by this database row
    """

    def to_objects(self, error_collector: ErrorCollector):
        raise NotImplemented()

    def __repr__(self):
        pass


def repr_no_raw(obj):
    fields = obj._asdict()
    del fields["raw_data"]
    return json.dumps(fields, indent=1, cls=DjangoJSONEncoder)


class DataFile(str, Enum):
    PPE_ORDERINGCHARTS_DATE_XLSX = "edc_ppe_data"
    SUPPLIERS_PARTNERS_XLSX = "edc_suppliers_partners"
    INVENTORY = "inventory"
    FACILITY_DELIVERIES = "facility_deliveries"
    HOSPITAL_DEMANDS = "hospital_demands"
    CSH_DONATIONS = "donations"
