name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the images
        run: docker-compose build
      - name: start everything
        run: docker-compose up -d && sleep 20
      - name: Test
        run: docker-compose exec backend python manage.py test
